"""Add document_id to sources

Revision ID: 008184bd94c7
Revises: 0002
Create Date: 2026-08-01 17:12:46.690132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '008184bd94c7'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analytics_events_created_at', table_name='analytics_events')
    op.drop_index('ix_analytics_events_event_type', table_name='analytics_events')
    op.drop_index('ix_analytics_events_user_id', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_user_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_documents_category', table_name='documents')
    op.drop_index('ix_documents_gr_number', table_name='documents')
    op.drop_index('ix_documents_supermemory_document_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_sources_message_id', table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('doc_type', postgresql.ENUM('PDF', 'DOCX', 'Circular', name='source_doc_type'), server_default=sa.text("'PDF'::source_doc_type"), autoincrement=False, nullable=False),
    sa.Column('page', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('section', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('snippet', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='sources_message_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sources_pkey')
    )
    op.create_index('ix_sources_message_id', 'sources', ['message_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=256), server_default=sa.text("'hte'::character varying"), autoincrement=False, nullable=False),
    sa.Column('file_type', postgresql.ENUM('PDF', 'DOCX', 'XLSX', name='doc_file_type'), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.VARCHAR(length=32), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('pages', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('tags', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=False),
    sa.Column('versions', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('visibility', postgresql.ENUM('public', 'internal', 'restricted', name='doc_visibility'), server_default=sa.text("'public'::doc_visibility"), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('uploaded', 'processing', 'indexed', 'failed', name='doc_status'), server_default=sa.text("'uploaded'::doc_status"), autoincrement=False, nullable=False),
    sa.Column('supermemory_document_id', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('ingestion_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gr_number', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('supersedes_gr', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('amends_gr', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='documents_uploaded_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='documents_pkey')
    )
    op.create_index('ix_documents_supermemory_document_id', 'documents', ['supermemory_document_id'], unique=False)
    op.create_index('ix_documents_gr_number', 'documents', ['gr_number'], unique=False)
    op.create_index('ix_documents_category', 'documents', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('student', 'faculty', 'officer', 'admin', name='user_role'), server_default=sa.text("'student'::user_role"), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=256), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'pending', name='user_status'), server_default=sa.text("'active'::user_status"), autoincrement=False, nullable=False),
    sa.Column('avatar', sa.VARCHAR(length=8), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('queries_this_month', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('last_active', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), server_default=sa.text("'New conversation'::character varying"), autoincrement=False, nullable=False),
    sa.Column('preview', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('message_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='conversations_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='conversations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_conversations_user_id', 'conversations', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('user', 'assistant', name='message_role'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence', postgresql.ENUM('high', 'medium', 'none', name='confidence_level'), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bookmarked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('feedback', postgresql.ENUM('helpful', 'not_helpful', name='message_feedback'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='messages_conversation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_type', postgresql.ENUM('chat_query', 'document_upload', 'document_search', 'user_login', 'rag_not_found', name='analytics_event_type'), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('supermemory_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('llm_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='analytics_events_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='analytics_events_pkey')
    )
    op.create_index('ix_analytics_events_user_id', 'analytics_events', ['user_id'], unique=False)
    op.create_index('ix_analytics_events_event_type', 'analytics_events', ['event_type'], unique=False)
    op.create_index('ix_analytics_events_created_at', 'analytics_events', ['created_at'], unique=False)
    # ### end Alembic commands ###
