"""Add GR Lineage

Revision ID: aab775396fc6
Revises: 0002
Create Date: 2026-08-02 01:32:45.983801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aab775396fc6'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gr_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_gr_id', sa.String(), nullable=False),
    sa.Column('target_gr_id', sa.String(), nullable=True),
    sa.Column('unresolved_reference', sa.String(length=256), nullable=True),
    sa.Column('relationship_type', sa.Enum('supersedes', 'amends', 'references', 'clarifies', name='gr_relationship_type'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_gr_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_gr_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gr_relationships_source_gr_id'), 'gr_relationships', ['source_gr_id'], unique=False)
    op.create_index(op.f('ix_gr_relationships_target_gr_id'), 'gr_relationships', ['target_gr_id'], unique=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_gr_relationships_target_gr_id'), table_name='gr_relationships')
    op.drop_index(op.f('ix_gr_relationships_source_gr_id'), table_name='gr_relationships')
    op.drop_table('gr_relationships')
    # ### end Alembic commands ###
